Dockerfiles: Fix Python package name causing build error
Error was:

  ERROR: unable to select packages:
    python (no such package):
      required by: world[python]